DROP TABLE IF EXISTS users ;

CREATE TABLE IF NOT EXISTS users (
    id INTEGER PRIMARY KEY AUTOINCREMENT,
    email VARCHAR(255) NOT NULL ,
    password VARCHAR(255) NOT NULL,
    secret VARCHAR(255) DEFAULT NULL 
);